"use client";

import {
  Home,
  Users,
  Settings,
  FileText,
  ShoppingCart,
  Plus,
  ScrollText,
  NotebookPen,
  BookOpenText,
  UserCog,
  UserRoundSearch,
  UsersRound,
  AreaChart,
  BarChartHorizontal,
  PieChart,
  Gauge,
  Bell,
  User,
  Folder,
  Cloud,
  File,
  Trash2,
  LayoutDashboard,
  ClipboardCheck,
  Calendar,
  UserPlus,
  UserCheck,
  Clock,
  Upload,
  Package,
  Box,
  LineChart,
  Ticket,
  Megaphone,
  IdCard,
  Shield,
  Lock,
  Palette,
  Globe,
} from "lucide-react";
import { SidebarItem } from "@/types/sidebar";

export const sidebarItems: SidebarItem[] = [
  {
    id: "dashboard",
    iconOutline: Home,
    iconSolid: Home,
    label: "Dashboard",
    subItems: [
      {
        label: "Analytics Overview",
        icon: AreaChart,
        href: "/protected/analytics-overview",
      },
      {
        label: "Recent Activity",
        icon: Bell,
        href: "/dashboard/recent-activity",
      },
      {
        label: "Quick Stats",
        icon: BarChartHorizontal,
        href: "/dashboard/quick-stats",
      },
      {
        label: "Performance Metrics",
        icon: Gauge,
        href: "/dashboard/performance-metrics",
      },
      { label: "Reports", icon: FileText, href: "/dashboard/reports" },
    ],
  },
  {
    id: "users",
    iconOutline: Users,
    iconSolid: Users,
    label: "ATS",
    subItems: [
      { label: "Overview", icon: LayoutDashboard, href: "/ats/overview" },
      { label: "Job Posting", icon: NotebookPen, href: "/ats/job-posting" },
      { label: "Assessment", icon: ClipboardCheck, href: "/ats/assessment" },
      { label: "Interview Plan", icon: Calendar, href: "/ats/interview-plan" },
      { label: "Recruiter", icon: UserRoundSearch, href: "/ats/recruiter" },
      {
        label: "Candidates",
        icon: UsersRound,
        subItems: [
          { label: "Leads", href: "/ats/candidates/leads", icon: Users },
          {
            label: "Interviewing",
            href: "/ats/candidates/interviewing",
            icon: Users,
          },
        ],
      },
      { label: "Reporting", icon: BarChartHorizontal, href: "/ats/reporting" },
    ],
  },
  {
    id: "documents",
    iconOutline: FileText,
    iconSolid: FileText,
    label: "Documents",
    subItems: [
      { label: "My Documents", icon: File, href: "/documents/my" },
      { label: "Shared Files", icon: Folder, href: "/documents/shared" },
      { label: "Recent Files", icon: Clock, href: "/documents/recent" },
      { label: "Upload New", icon: Upload, href: "/documents/upload" },
      { label: "Trash", icon: Trash2, href: "/documents/trash" },
      { label: "Cloud Storage", icon: Cloud, href: "/documents/cloud" },
    ],
  },
  {
    id: "ecommerce",
    iconOutline: ShoppingCart,
    iconSolid: ShoppingCart,
    label: "E-commerce",
    subItems: [
      { label: "Orders", icon: Package, href: "/ecommerce/orders" },
      { label: "Products", icon: Box, href: "/ecommerce/products" },
      { label: "Customers", icon: Users, href: "/ecommerce/customers" },
      {
        label: "Sales Reports",
        icon: LineChart,
        href: "/ecommerce/sales-reports",
      },
      { label: "Coupons", icon: Ticket, href: "/ecommerce/coupons" },
      { label: "Marketing", icon: Megaphone, href: "/ecommerce/marketing" },
    ],
  },
  {
    id: "settings",
    iconOutline: Settings,
    iconSolid: Settings,
    label: "Settings",
    subItems: [
      { label: "Profile Settings", icon: User, href: "/settings/profile" },
      { label: "Account Settings", icon: IdCard, href: "/settings/account" },
      { label: "Privacy", icon: Shield, href: "/settings/privacy" },
      { label: "Notifications", icon: Bell, href: "/settings/notifications" },
      { label: "Security", icon: Lock, href: "/settings/security" },
      { label: "Appearance", icon: Palette, href: "/settings/appearance" },
      { label: "Language", icon: Globe, href: "/settings/language" },
    ],
  },
];
